lovestruck/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('accounts/signup/', views.signup, name='signup'),
    path('', views.home, name='home'),
    path('locations/', views.LocationList.as_view(), name='location_index'),
    path('locations/create/', views.LocationCreate.as_view(), name='location_create'),
    path('locations/<int:pk>/', views.LocationDetail.as_view(), name='location_detail'),
    path('locations/<int:pk>/update', views.LocationUpdate.as_view(), name='location_update'),
    path('locations/<int:pk>/delete', views.LocationDelete.as_view(), name='location_delete'),
    path('partners/', views.PartnerList.as_view(), name='partner_index'),
    path('partners/create/', views.PartnerCreate.as_view(), name='partner_create'),
    path('partners/<int:pk>/', views.PartnerDetail.as_view(), name='partner_detail'),
    path('partners/<int:pk>/update', views.PartnerUpdate.as_view(), name='partner_update'),
    path('partners/<int:pk>/delete', views.PartnerDelete.as_view(), name='partner_delete'),
    path('dates/', views.DateList.as_view(), name='date_index'),
    path('dates/create/', views.DateCreate.as_view(), name='date_create'),
    path('dates/<int:pk>/', views.DateDetail.as_view(), name='date_detail'),
    path('dates/<int:pk>/update/', views.DateUpdate.as_view(), name='date_update'),
    path('dates/<int:pk>/delete/', views.DateDelete.as_view(), name='date_delete'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date

# Create your models here.


class Location(models.Model):
  name = models.CharField(max_length=100)
  address = models.CharField(max_length=200)
  phone_num = models.CharField(max_length=14)
  city = models.CharField(max_length=50)
  state = models.CharField(max_length=2)
  category = models.CharField(max_length=50)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self): 
    return f'Name: {self.name}, ({self.id})'

  def get_absolute_url(self):
    return reverse('location_detail', kwargs={'pk': self.id})


class Partner(models.Model):
  name = models.CharField(max_length=100)
  notes = models.TextField(max_length=1000, blank=True)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return f'Name: {self.name}, ({self.id})'

  def get_absolute_url(self):
    return reverse('partner_detail', kwargs={'pk': self.id})


class Date(models.Model):
  activity = models.CharField(max_length=200)
  budget = models.PositiveIntegerField(null=True)
  rating = models.PositiveIntegerField(null=True)
  date = models.DateField()
  notes = models.TextField(max_length=1000, blank=True)
  location = models.ForeignKey(Location, on_delete=models.CASCADE)
  partner = models.ForeignKey(Partner, on_delete=models.CASCADE)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return f'Date: {self.activity} ({self.id})'

  def get_absolute_url(self):
    return reverse('date_detail', kwargs={'pk': self.id})

  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Date

class DateForm(ModelForm):
    class Meta:
        model = Date
        fields = ['date', 'activity', 'budget', 'notes']

main_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import Location, Partner, Date
from .forms import DateForm
from datetime import date


# Create your views here.
def home(request):
    if request.user.is_authenticated:
        dates = Date.objects.filter(user=request.user, date=date.today())
    else:
        dates = ''
    return render(request, 'home.html', {'dates':dates})

def signup(request): 
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


class LocationList(ListView):
    model = Location
    fields = ['name', 'category', 'city', 'state']


class LocationCreate(LoginRequiredMixin, CreateView):
    model = Location
    fields = ['name', 'address', 'phone_num', 'city', 'state', 'category']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class LocationDetail(LoginRequiredMixin, DetailView):
    model = Location
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['partner_list'] = Partner.objects.filter(user=self.request.user)
        context['date_form'] = DateForm()
        return context


class LocationUpdate(LoginRequiredMixin, UpdateView):
    model = Location
    fields = ['name', 'address', 'phone_num', 'city', 'state', 'category']


class LocationDelete(LoginRequiredMixin, DeleteView):
    model = Location
    success_url = '/locations/'


class PartnerList(LoginRequiredMixin, ListView):
    model = Partner
    fields = ['name']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['partner_list'] = Partner.objects.filter(
            user=self.request.user)
        return context


class PartnerCreate(LoginRequiredMixin, CreateView):
    model = Partner
    fields = ['name', 'notes']
    success_url = '/partners/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PartnerDetail(LoginRequiredMixin, DetailView):
    model = Partner
    fields = '__all__'


class PartnerUpdate(LoginRequiredMixin, UpdateView):
    model = Partner
    fields = ['name', 'notes']


class PartnerDelete(LoginRequiredMixin, DeleteView):
    model = Partner
    success_url = '/partners/'


class DateList(LoginRequiredMixin, ListView):
    model = Date
    fields = ['location', 'partner']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['date_list'] = Date.objects.filter(
            user=self.request.user)
        return context


class DateCreate(LoginRequiredMixin, CreateView):
    model = Date
    form_class = DateForm

    def form_valid(self, form):
        form.instance.partner_id = self.request.POST.get('partner_id')
        form.instance.location_id = self.request.POST.get('location_id')
        form.instance.user = self.request.user
        return super().form_valid(form)
    success_url = '/dates/'


class DateDetail(LoginRequiredMixin, DetailView):
    model = Date

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['partner_list'] = Partner.objects.filter(
            user=self.request.user)
        return context

class DateUpdate(LoginRequiredMixin, UpdateView):
    model = Date
    fields = ['activity', 'date', 'budget', 'rating', 'notes']


class DateDelete(LoginRequiredMixin, DeleteView):
    model = Date
    success_url = '/dates/'

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LoveStruck</title>
    <!-- Materialize Stylesheets -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <!-- Stylesheets -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Materialize Scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <ul id="dropdown1" class="dropdown-content">
        <li><a href="{% url 'location_index' %}">View All Date Spots</a></li>
        <li><a href="{% url 'location_create' %}">Add a Date Spot</a></li>
    </ul>
    <ul id="dropdown2" class="dropdown-content">
        <li><a href="{% url 'partner_index' %}">View All Partners</a></li>
        <li><a href="{% url 'partner_create' %}">Add a Partner</a></li>
    </ul>
    <nav>
        {% if user.is_authenticated %}
        <div class="nav-wrapper">
                <a class="brand-logo left" href="{% url 'home' %}">LoveStruck</a>
                <div class="right flex-nav">
                    <a class="padding" href="{% url 'date_index' %}">View All Dates</a>
                    <ul>
                        <!-- Dropdown Trigger -->
                        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Locations</a></li>
                    </ul>
                    <ul>
                        <!-- Dropdown Trigger -->
                        <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Partners</a></li>
                    </ul>
                    <a class="padding" href="{% url 'logout' %}">Log Out</a>
                </div>
            </div>
        {% else %}
            <a class="brand-logo" href="{% url 'home' %}">LoveStruck</a>
            <div class="logged-out-flex-nav">
                <a href="{% url 'location_index' %}">Locations</a>
                <a href="{% url 'login' %}">Log In</a>
                <a href="{% url 'signup' %}">Sign Up</a>
            </div>
        {% endif %}
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>

<script>
     document.addEventListener('DOMContentLoaded', function () {
        var elems = document.querySelectorAll('.dropdown-trigger');
        var instances = M.Dropdown.init(elems, alignment='right');
        });
</script>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

{% if user.is_authenticated %}
{% if dates.count == 0 %}
<h2 class="center margin-top">Schedule a Date Today</h2>
{% else %}
<h2 class="center margin-top">You Have a Date Today!</h2>
{% endif %}
{% for date in dates %}
<div class="container">
      <div class="card home-card">
        <div class="card-image">
          <img src="static/images/datenight.jpeg" alt="date-night-photo">
          <a href="{% url 'date_detail' date.id %}" class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">+</i></a>
        </div>
        <div class="card-content">
          <p>{{ date.activity }}</p>
        </div>
      </div>
</div>
	{% endfor %}
{% else %}
	<section class="colored-section">
		<div class="container">
			<div class="row">
				<div class="col s6">
					<h2>Find the perfect spot for any new date!</h2>
				</div>
				<div class="col s6">
					<img class="center" src="static/images/couple.jpg" alt="couple photo">
				</div>
			</div>
		</div>
	</section>
	<section class="white-section">
		<div class="container">
			<div class="row">
				<div class="col s12 m4 center">
					<h3 class="margin feature-title">Easy to use</h3>
					<p>An easy way to plan and manage upcoming dates.</p>
				</div>
		
				<div class="col s12 m4 center">
					<h3 class="margin feature-title">Find the best date spots</h3>
					<p>See where our users are going out.</p>
				</div>
		
				<div class="col s12 m4 center">
					<h3 class="margin feature-title">Never miss a detail for dates</h3>
					<p>Easily track notes on locations and partners in our user-friendly app.</p>
				</div>
			</div>
		</div>
	</section>
	<section class="colored-section">
		<div class="container">
			<div class="row">
				<div class="col center s12 m4">
					<div class="card">
						<div class="card-content">
							<span class="card-title black-text"><h5>Free</h5></span>
							<p>Sign up for a free account and start planning your next date!</p>
						</div>
						<div class="card-action blue-grey lighten-3">
							<button class="btn" type="submit"><a class="white-text" href="{% url 'signup' %}">Sign Up</a></button>
						</div>
					</div>
				</div>
				<div class="col center s6 m4">
					<div class="card">
						<div class="card-content">
							<span class="card-title black-text"><h5>$10/Month</h5></span>
							<p>Sign up for a free account and start planning your next date!</p>
						</div>
						<div class="card-action blue-grey lighten-3">
							<button class="btn" type="submit"><a class="white-text" href="{% url 'signup' %}">Sign Up</a></button>
						</div>
					</div>
				</div>
				<div class="col center s6 m4">
					<div class="card">
						<div class="card-content">
							<span class="card-title black-text"><h5>$100/Year</h5></span>
							<p>Sign up for a free account and start planning your next date!</p>
						</div>
						<div class="card-action blue-grey lighten-3">
							<button class="btn" type="submit"><a class="white-text" href="{% url 'signup' %}">Sign Up</a></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

{% endif %}

{% endblock %}

main_app/templates/main_app/date_confirm_delete.html
{% extends 'base.html' %}
{% block content%}
<h1 class="center">Delete Date</h1>
<div class="container">
  <div class="delete-grid">
    <h4 class="s2">Are you sure you want to delete this date?</h4>
    <form class="s2 flex-row" action="" method="POST">
      {% csrf_token %}
      <input type="submit" class="btn delete-btn" value="Delete">
      <button class="btn" type="submit"><a href="{% url 'date_detail' date.id%}">Cancel</a></button>
    </form>
  </div>
</div>

{% endblock %}

main_app/templates/main_app/date_detail.html
{% extends 'base.html' %}
{% block content %}
<h1 class="center">Date Details</h1>
<div class="container">
	<div class="date-grid">
		<h4>Activity</h4>
		<p>{{ date.activity }}</p>
		<h4>Budget</h4>
		<p>{{ date.budget }}</p>
		<h4>Rating</h4>
		<p>{{ date.rating }}</p>
		<h4>Notes</h4>
		<p>{{ date.notes }}</p>
		<h4>Date</h4>
		<p>{{ date.date }}</p>
		<h4>Partner</h4>
		<p>{{ date.partner.name }}</p>
		<h4>Location</h4>
		<p>{{ date.location.name }}</p>
		<a class="justify-self" href="{% url 'date_update' date.id %}"><button type="submit" class="btn">Edit</button></a>
		<a class="justify-self" href="{% url 'date_delete' date.id %}"><button type="submit" class="btn">Delete</button></a>
	</div>
</div>

{% endblock %}

main_app/templates/main_app/date_form.html
{% extends 'base.html' %}
{% block content %}
<h1 class="center">Edit Date</h1>
<form class="flex-form" action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button class="btn s2" type="submit">Submit</button>
</form>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
</script>
{% endblock %}

main_app/templates/main_app/date_list.html
{% extends 'base.html' %}
{% block content %}
{% if date_list.count == 0 %}
	<h1 class="center">No Dates Scheduled Yet</h1>
	<div class="container">
		<div class="box">
			<h5>See our list of date spots for future dates</h3>
			<a href="{% url 'location_index' %}"><button class="btn">View All Locations</button></a>
		</div>
	</div>
{% else %}
	<h1 class="center">All Dates</h1>
	<div class="container">
		<div class="index-grid">
			{% for date in date_list %}
				<div class="card">
					<div class="card-content">
						<span class="card-title">{{ date.activity }}</span>
						<p>Partner: &nbsp;{{ date.partner.name }}</p>
						<p>Date: &nbsp;{{ date.date }}</p>
					</div>
					<div class="card-action">
						<a href="{% url 'date_detail' date.id %}"> View Details</a>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endif %}
{% endblock %}

main_app/templates/main_app/location_confirm_delete.html
{% extends 'base.html' %}
{% block content%}
<h1 class="center">Delete Location</h1>
<div class="container">
	<div class="delete-grid">
		<h4 class="s2">Are you sure you want to delete {{ object.name }}?</h4>
		<form class="s2 flex-row" action="" method="POST">
			{% csrf_token %}
			<input type="submit" class="btn delete-btn" value="Delete">
			<a href="{% url 'location_detail' location.id%}"><button class="btn" type="submit">Cancel</button></a>
		</form>
	</div>
</div>

{% endblock %}

main_app/templates/main_app/location_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
	<h1 class="center">{{ location.name }} Details</h1>
	<div class="ld-detail-grid">
		<div id="location-info" class="location-grid">
			<h4 class="s2 center">Location Information</h4>
			<h5>Address:</h5>
			<p>{{location.address}}</p>
			<h5>Phone Number:</h5>
			<p>{{location.phone_num}}</p>
			<h5>City:</h5>
			<p>{{location.city}}</p>
			<h5>State:</h5>
			<p>{{location.state}}</p>
			<h5>Category:</h5>
			<p>{{location.category}}</p>
			{% if user == location.user %}
			<button type="submit" class="btn"><a href="{% url 'location_update' location.id %}">Edit</a></button>
			<button type="submit" class="btn"><a href="{% url 'location_delete' location.id %}">Delete</a></button>
			{% endif %}
		</div>
		<div>
			{% if partner_list.count > 0 %}
				<form id="add-date-form" class="location-grid flex-form" action="{% url 'date_create' %}" method="POST">
					<h4 class="s2 center">You can't go by yourself... </h4>
					{% csrf_token %}
					<label for="partner_listing">Choose a Partner:</label>
					<select name="partner_id" id="partner_listing">
						{% for partner in partner_list %}
						<option value="{{ partner.id }}">{{ partner.name }}</option>
						{% endfor %}
					</select>
					{{ date_form }}
					<input type="hidden" name="location_id" value="{{ location.id }}">
					<button class="btn s2" type="submit">Add a Date</button>
				</form>
			{% else %}
				<h4 class="center">You haven't added anyone to go out with yet...</h4>
				<div class="box">
					<h5>Click here to add some partners!</h3>
						<a href="{% url 'partner_create' %}"><button class="btn">Add Partner</button></a>
				</div>
			{% endif %}
		</div>
	</div>
</div>

<script>
	const dateEl = document.getElementById('id_date');
	M.Datepicker.init(dateEl, {
		format: 'yyyy-mm-dd',
		defaultDate: new Date(),
		setDefaultDate: true,
		autoClose: true
	});
</script>

{% endblock %}

main_app/templates/main_app/location_form.html
{% extends 'base.html' %}
{% block content %}
{% if object %}
	<h1 class="center">Edit Location</h1>
{% else %}
	<h1 class="center">Add Location</h1>
{% endif %}
<form class="flex-form" action="" method="POST">
	{% csrf_token %}
	<table>
	{{ form }}
	</table>
	<button class="btn" type="submit">Submit</button>
</form>

{% endblock %}

main_app/templates/main_app/location_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
	<h1 class="center">Location List</h1>
	<div class="index-grid">
		{% for l in location_list %}
			<div class="card">
				<div class="card-content">
					<span class="card-title">{{ l.name }}</span>
					<p>City: &nbsp;{{ l.city }}</p>
					<p>State: &nbsp;{{ l.state }}</p>
					<p>Category: &nbsp;{{ l.category }}</p>
				</div>
				<div class="card-action">
					<a href="{% url 'location_detail' l.id %}"> View Details</a>
				</div>
			</div>
		{% endfor %}
	</div>
</div>

{% endblock %}

main_app/templates/main_app/partner_confirm_delete.html
{% extends 'base.html' %}
{% block content%}
<h1 class="center">Delete Partner</h1>
<div class="container">
  <div class="delete-grid">
    <h4 class="s2">Are you sure you want to delete {{ object.name }}?</h4>
    <form class="s2 flex-row" action="" method="POST">
      {% csrf_token %}
      <input type="submit" class="btn delete-btn" value="Delete">
      <a href="{% url 'partner_detail' partner.id%}"><button type="submit" class="btn">Cancel</button></a>
    </form>
  </div>
</div>

{% endblock %}

main_app/templates/main_app/partner_detail.html
{% extends 'base.html' %}
{% block content %}
<h1 class="center">Partner Details</h1>
<div class="container">
  <div class="card partner-card">
    <div class="s2 card-content partner-grid">
      <span class="card-title center s2">{{ partner.name }}</span>
      <h4>Date Count:</h4>
      <h4>{{ partner.date_set.count }}</h4>
      <p class="s2">{{ partner.notes }}</p>
    </div>
    <div class="card-action flex-row s2">
      <button class="btn"><a href="{% url 'partner_update' partner.id %}">Edit</a></button>
      <button class="btn"><a href="{% url 'partner_delete' partner.id %}">Delete</a></button>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/partner_form.html
{% extends 'base.html' %}
{% block content %}
{% if object %}
  <h1 class="center">Edit Partner</h1>
{% else %}
  <h1 class="center">Add a Partner</h1>
{% endif %}
<form class="flex-form" action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input class="btn" type="submit" value="Submit">
</form>
{% endblock %}

main_app/templates/main_app/partner_list.html
{% extends 'base.html' %}
{% block content %}
{% if partner_list.count == 0 %}
	<h1 class="center">No Partners Added Yet</h1>
	<div class="container">
		<div class="box">
			<h5>Don't worry, you'll find someone. When you do add them here!</h5>
				<a href="{% url 'partner_create' %}"><button class="btn">Add a Partner</button></a>
		</div>
	</div>
{% else %}
	<h1 class="center">Partners</h1>
	<div class="container">
		<div class="index-grid">
			{% for person in partner_list %}
				<div class="card">
				<div class="card-content">
					<span class="card-title">{{ person.name }}</span>
					<p>Notes: &nbsp;{{ person.notes }}</p>
				</div>
				<div class="card-action">
					<a href="{% url 'partner_detail' person.id %}"> View Details</a>
				</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endif %}
{% endblock %}